---
title: "&nbsp;"
output: pdf_document
classoption: landscape
---

```{r, echo = F}
library(flextable)
```


# 5 success
# 5 accuracy
# 3 accuracy
# Bulk accuracy
# DRB345 accuracy
# Time point accuracy
# Composite accuracy

\newpage
# 5 success
```{r, echo = F, warning = F}
p5_success_flextable <- readRDS("tables/p5_success_flextable.RDS")
set_table_properties(p5_success_flextable, layout = "autofit") 
```

\newpage
# 5 accuracy
```{r, echo = F, warning = F}
p5_accuracy_flextable <- readRDS("tables/p5_accuracy_flextable.RDS")
set_table_properties(p5_accuracy_flextable, layout = "autofit") 
```

\newpage
# 3 accuracy
```{r, echo = F, warning = F}
p3_accuracy_flextable <- readRDS("tables/p3_accuracy_flextable.RDS")
set_table_properties(p3_accuracy_flextable, layout = "autofit") 
```

\newpage
# Bulk accuracy
```{r, echo = F, warning = F}
bulk_accuracy_flextable <- readRDS("tables/bulk_accuracy_flextable.RDS")
set_table_properties(bulk_accuracy_flextable, layout = "autofit") 
```

\newpage
# DRB345 accuracy
```{r, echo = F, warning = F}
drb345_flextable <- readRDS("tables/drb345_flextable.RDS")
set_table_properties(drb345_flextable, layout = "autofit") 
```
|       **Supplemental Table X - *HLA-DRB345* accuracy**
|       Accuracy of *HLA-DRB345* genotypes filtered or unfiltered by KNN copy number classifier. Values represent mean accuracy +/- SEM




